/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#include "probData.h"



void custom_KKT_solve(REAL y[3], REAL x[3]) {
copy_vector(y,x,3);
ldl_lapack_solve(KKT_lp, y);
}

void custom_compute_prefactor() {
ldl_lapack_prefactor(KKT_lp);
}

void loadData() {
Data *dat = splitLoad("probData.dat");
copyVar(rhs, dat, "rhs");
copyVar(KKT_lp, dat, "KKT_lp");
freeData(dat);
}

