/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#ifndef __harshdata_h__
#define __harshdata_h__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <Accelerate/Accelerate.h>
#include "matrix_ops.h"
#include "splitLoad.h"

typedef double REAL;
#define printVec printDoubleVec
__CLPK_integer ipiv[];

#define rhs_rows 3
#define rhs_cols 1
#define rhs_len 3
double rhs[3];

#define KKT_lp_rows 9
#define KKT_lp_cols 1
#define KKT_lp_len 9
double KKT_lp[9];

#define nn_lp_rows 1
#define nn_lp_cols 1
#define nn_lp_len 1
int nn_lp[1];


// Functions
void custom_KKT_solve(REAL y[3], REAL x[3]);
void custom_compute_prefactor();
void loadData();


#endif
