/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#ifndef __user_probData_h__
#define __user_probData_h__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "user_matrix_ops.h"
typedef double REAL;
#define printVec printDoubleVec
#define nParam 8
#define nPrimal 68
#define nDual 40
#define nEqCon 48
extern const REAL rho;

extern const REAL rhoinv; 

extern REAL prox_var; 

#define nn_lp 116
#define LNZ_ss 483
#define ANZ_ss 551
#define N_ss 116

#define par_ex_rows 8
#define par_ex_cols 1
#define par_ex_len 8
extern double par_ex[8];

#define sol_x_rows 68
#define sol_x_cols 1
#define sol_x_len 68
extern double sol_x[68];

#define sol_lam_rows 40
#define sol_lam_cols 1
#define sol_lam_len 40
extern double sol_lam[40];

#define sol_y_rows 40
#define sol_y_cols 1
#define sol_y_len 40
extern double sol_y[40];

#define l_rows 40
#define l_cols 1
#define l_len 40
extern double l[40];

#define f_rows 68
#define f_cols 1
#define f_len 68
extern double f[68];

#define b_rows 48
#define b_cols 1
#define b_len 48
extern double b[48];

#define _var_1__b_rows 48
#define _var_1__b_cols 1
#define _var_1__b_len 48
extern double _var_1__b[48];

#define Ltrans_rind_rows 40
#define Ltrans_rind_cols 1
#define Ltrans_rind_len 40
extern int Ltrans_rind[40];

#define Ltrans_cind_rows 40
#define Ltrans_cind_cols 1
#define Ltrans_cind_len 40
extern int Ltrans_cind[40];

#define Ltrans_val_rows 40
#define Ltrans_val_cols 1
#define Ltrans_val_len 40
extern double Ltrans_val[40];

#define KKT_rows 116
#define KKT_cols 68
#define KKT_len 7888
extern double KKT[7888];

#define L_rind_rows 40
#define L_rind_cols 1
#define L_rind_len 40
extern int L_rind[40];

#define L_cind_rows 40
#define L_cind_cols 1
#define L_cind_len 40
extern int L_cind[40];

#define L_val_rows 40
#define L_val_cols 1
#define L_val_len 40
extern double L_val[40];
#ifdef lapack_linsolve 
extern __CLPK_integer ipiv[nn_lp];
#endif 
extern double *Lx_ss;
extern int *Li_ss;


// Functions
void custom_compute_parametric(REAL l[40], REAL f[68], REAL b[48], REAL par[8]);
void compute_parametric_pB(REAL y[48], REAL x[8]);
void custom_mult_Ltrans(REAL y[68], REAL x[40]);
/*
invert_FPGA
*/
void custom_solve_kkt(REAL y[116], REAL x[116]);
void custom_compute_prefactor();
void custom_mult_L(REAL workDual[40], REAL x[68]);
void custom_prox(double y[nDual], double x[nDual]);


#endif
