/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#ifndef __user_probData_h__
#define __user_probData_h__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "user_matrix_ops.h"
typedef double REAL;
#define printVec printDoubleVec
#define nParam 4
#define nPrimal 46
#define nDual 28
#define nEqCon 32
extern const REAL rho;

extern const REAL rhoinv; 

extern REAL prox_var; 

#define nn_lp 78
#define LNZ_ss 186
#define ANZ_ss 232
#define N_ss 78

#define par_ex_rows 4
#define par_ex_cols 1
#define par_ex_len 4
extern double par_ex[4];

#define sol_x_rows 46
#define sol_x_cols 1
#define sol_x_len 46
extern double sol_x[46];

#define sol_lam_rows 28
#define sol_lam_cols 1
#define sol_lam_len 28
extern double sol_lam[28];

#define sol_y_rows 28
#define sol_y_cols 1
#define sol_y_len 28
extern double sol_y[28];

#define l_rows 28
#define l_cols 1
#define l_len 28
extern double l[28];

#define f_rows 46
#define f_cols 1
#define f_len 46
extern double f[46];

#define b_rows 32
#define b_cols 1
#define b_len 32
extern double b[32];

#define _var_1__b_rows 32
#define _var_1__b_cols 1
#define _var_1__b_len 32
extern double _var_1__b[32];

#define Ltrans_p_ss_rows 29
#define Ltrans_p_ss_cols 1
#define Ltrans_p_ss_len 29
extern int Ltrans_p_ss[29];

#define Ltrans_i_ss_rows 28
#define Ltrans_i_ss_cols 1
#define Ltrans_i_ss_len 28
extern int Ltrans_i_ss[28];

#define Ltrans_x_ss_rows 28
#define Ltrans_x_ss_cols 1
#define Ltrans_x_ss_len 28
extern double Ltrans_x_ss[28];

#define n_Ltrans_ss_rows 1
#define n_Ltrans_ss_cols 1
#define n_Ltrans_ss_len 1
extern int n_Ltrans_ss[1];

#define KKT_rows 78
#define KKT_cols 46
#define KKT_len 3588
extern double KKT[3588];

#define L_p_ss_rows 47
#define L_p_ss_cols 1
#define L_p_ss_len 47
extern int L_p_ss[47];

#define L_i_ss_rows 28
#define L_i_ss_cols 1
#define L_i_ss_len 28
extern int L_i_ss[28];

#define L_x_ss_rows 28
#define L_x_ss_cols 1
#define L_x_ss_len 28
extern double L_x_ss[28];

#define n_L_ss_rows 1
#define n_L_ss_cols 1
#define n_L_ss_len 1
extern int n_L_ss[1];
#ifdef lapack_linsolve 
extern __CLPK_integer ipiv[nn_lp];
#endif 
extern double *Lx_ss;
extern int *Li_ss;


// Functions
void custom_compute_parametric(REAL l[28], REAL f[46], REAL b[32], REAL par[4]);
void compute_parametric_pB(REAL y[32], REAL x[4]);
void custom_mult_Ltrans(REAL y[46], REAL x[28]);
/*
invert_FPGA
*/
void custom_solve_kkt(REAL y[78], REAL x[78]);
void custom_compute_prefactor();
void custom_mult_L(REAL workDual[28], REAL x[46]);
void custom_prox(double y[nDual], double x[nDual]);


#endif
