/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#ifndef __user_probData_h__
#define __user_probData_h__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "user_matrix_ops.h"

//#ifndef __user_probData_FPGA_h__
//#include "user_probdata_FPGA.h"
//#endif

typedef double REAL;
#define printVec printDoubleVec
#define nParam 4
#define nPrimal 34
#define nDual 50
#define nEqCon 24
extern const REAL rho;

extern const REAL rhoinv; 

extern REAL prox_var; 

#define nn_lp 58
#define LNZ_ss 134
#define ANZ_ss 168
#define N_ss 58

#define par_ex_rows 4
#define par_ex_cols 1
#define par_ex_len 4
extern double par_ex[4];

#define sol_x_rows 34
#define sol_x_cols 1
#define sol_x_len 34
extern double sol_x[34];

#define sol_lam_rows 50
#define sol_lam_cols 1
#define sol_lam_len 50
extern double sol_lam[50];

#define sol_y_rows 50
#define sol_y_cols 1
#define sol_y_len 50
extern double sol_y[50];

#define l_rows 50
#define l_cols 1
#define l_len 50
extern double l[50];

#define f_rows 34
#define f_cols 1
#define f_len 34
extern double f[34];

#define b_rows 24
#define b_cols 1
#define b_len 24
extern double b[24];

#define _var_1__b_rows 24
#define _var_1__b_cols 1
#define _var_1__b_len 24
extern double _var_1__b[24];

#define Ltrans_p_ss_rows 51
#define Ltrans_p_ss_cols 1
#define Ltrans_p_ss_len 51
extern int Ltrans_p_ss[51];

#define Ltrans_i_ss_rows 50
#define Ltrans_i_ss_cols 1
#define Ltrans_i_ss_len 50
extern int Ltrans_i_ss[50];

#define Ltrans_x_ss_rows 50
#define Ltrans_x_ss_cols 1
#define Ltrans_x_ss_len 50
extern double Ltrans_x_ss[50];

#define n_Ltrans_ss_rows 1
#define n_Ltrans_ss_cols 1
#define n_Ltrans_ss_len 1
extern int n_Ltrans_ss[1];

#define KKT_L_iDiag_rows 58
#define KKT_L_iDiag_cols 1
#define KKT_L_iDiag_len 58
extern double KKT_L_iDiag[58];

#define KKT_L_lower_tri_rows 58
#define KKT_L_lower_tri_cols 58
#define KKT_L_lower_tri_len 3364

#define KKT_L_lower_tri_nz_per_row_rows 1
#define KKT_L_lower_tri_nz_per_row_cols 58
#define KKT_L_lower_tri_nz_per_row_len 58
extern int KKT_L_lower_tri_nz_per_row[58];

#define KKT_L_lower_tri_ind_rows 1
#define KKT_L_lower_tri_ind_cols 278
#define KKT_L_lower_tri_ind_len 278
extern int KKT_L_lower_tri_ind[278];

#define KKT_L_lower_tri_dat_rows 1
#define KKT_L_lower_tri_dat_cols 278
#define KKT_L_lower_tri_dat_len 278
extern double KKT_L_lower_tri_dat[278];

#define KKT_L_p_rows 1
#define KKT_L_p_cols 58
#define KKT_L_p_len 58
extern int KKT_L_p[58];

#define KKT_L_s_rows 58
#define KKT_L_s_cols 1
#define KKT_L_s_len 58
extern double KKT_L_s[58];

#define _var_4__p_ss_rows 59
#define _var_4__p_ss_cols 1
#define _var_4__p_ss_len 59
extern int _var_4__p_ss[59];

#define _var_4__i_ss_rows 58
#define _var_4__i_ss_cols 1
#define _var_4__i_ss_len 58
extern int _var_4__i_ss[58];

#define _var_4__x_ss_rows 58
#define _var_4__x_ss_cols 1
#define _var_4__x_ss_len 58
extern double _var_4__x_ss[58];

#define n__var_4__ss_rows 1
#define n__var_4__ss_cols 1
#define n__var_4__ss_len 1
extern int n__var_4__ss[1];

#define KKT_LT_iDiag_rows 58
#define KKT_LT_iDiag_cols 1
#define KKT_LT_iDiag_len 58
extern double KKT_LT_iDiag[58];

#define KKT_LT_upper_tri_rows 58
#define KKT_LT_upper_tri_cols 58
#define KKT_LT_upper_tri_len 3364

#define KKT_LT_upper_tri_nz_per_row_rows 1
#define KKT_LT_upper_tri_nz_per_row_cols 58
#define KKT_LT_upper_tri_nz_per_row_len 58
extern int KKT_LT_upper_tri_nz_per_row[58];

#define KKT_LT_upper_tri_ind_rows 1
#define KKT_LT_upper_tri_ind_cols 278
#define KKT_LT_upper_tri_ind_len 278
extern int KKT_LT_upper_tri_ind[278];

#define KKT_LT_upper_tri_dat_rows 1
#define KKT_LT_upper_tri_dat_cols 278
#define KKT_LT_upper_tri_dat_len 278
extern double KKT_LT_upper_tri_dat[278];

#define KKT_LT_s_rows 58
#define KKT_LT_s_cols 1
#define KKT_LT_s_len 58
extern double KKT_LT_s[58];

#define L_p_ss_rows 35
#define L_p_ss_cols 1
#define L_p_ss_len 35
extern int L_p_ss[35];

#define L_i_ss_rows 50
#define L_i_ss_cols 1
#define L_i_ss_len 50
extern int L_i_ss[50];

#define L_x_ss_rows 50
#define L_x_ss_cols 1
#define L_x_ss_len 50
extern double L_x_ss[50];

#define n_L_ss_rows 1
#define n_L_ss_cols 1
#define n_L_ss_len 1
extern int n_L_ss[1];
#ifdef lapack_linsolve 
extern __CLPK_integer ipiv[nn_lp];
#endif 
extern double *Lx_ss;
extern int *Li_ss;


// Functions
void custom_compute_parametric(REAL l[50], REAL f[34], REAL b[24], REAL par[4]);
void compute_parametric_pB(REAL y[24], REAL x[4]);
void custom_mult_Ltrans(REAL y[34], REAL x[50]);
/*
ldl
*/
void custom_solve_kkt(REAL y[58], REAL x[58]);
void custom_solve_kkt_solve1(double _x[58], double _b[58]);
void custom_solve_kkt_solve2(REAL y[58], REAL x[58]);
void custom_solve_kkt_solve3(double _x[58], double _z[58]);
void custom_compute_prefactor();
void custom_mult_L(REAL workDual[50], REAL x[34]);
void custom_prox(double y[nDual], double x[nDual]);
//void loaddata();

#endif
