/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#ifndef __user_probData_h__
#define __user_probData_h__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "foo_data.h"
#include "user_matrix_ops.h"
#define real data_t_primal_out
#define REAL data_t_primal_out
#define nParam 20
#define nPrimal 230
#define nDual 140
#define nEqCon 160
#define rho_init 0.050000
#define rho_inv_init 20.000000
#define prox_var_init 0.000000
extern real rho;

extern real rhoinv; 

extern real prox_var; 

#define nn_lp 390
#define LNZ_ss 4360
#define ANZ_ss 4590
#define N_ss 390
#define suitesparse_linsolve


#define par_ex_rows 20
#define par_ex_cols 1
#define par_ex_len 20
extern real par_ex[20];

#define sol_x_rows 230
#define sol_x_cols 1
#define sol_x_len 230
extern real sol_x[230];

#define sol_lam_rows 140
#define sol_lam_cols 1
#define sol_lam_len 140
extern real sol_lam[140];

#define sol_y_rows 140
#define sol_y_cols 1
#define sol_y_len 140
extern real sol_y[140];

#define l_rows 140
#define l_cols 1
#define l_len 140
extern real l[140];

#define f_rows 230
#define f_cols 1
#define f_len 230
extern real f[230];

#define b_rows 160
#define b_cols 1
#define b_len 160
extern real b[160];

#define _var_1__b_rows 160
#define _var_1__b_cols 1
#define _var_1__b_len 160
extern real _var_1__b[160];

#define Ltrans_p_ss_rows 141
#define Ltrans_p_ss_cols 1
#define Ltrans_p_ss_len 141
extern int Ltrans_p_ss[141];

#define Ltrans_i_ss_rows 140
#define Ltrans_i_ss_cols 1
#define Ltrans_i_ss_len 140
extern int Ltrans_i_ss[140];

#define Ltrans_x_ss_rows 140
#define Ltrans_x_ss_cols 1
#define Ltrans_x_ss_len 140
extern real Ltrans_x_ss[140];

#define n_Ltrans_ss_rows 1
#define n_Ltrans_ss_cols 1
#define n_Ltrans_ss_len 1
extern int n_Ltrans_ss[1];

#define Ap_ss_rows 391
#define Ap_ss_cols 1
#define Ap_ss_len 391
extern int Ap_ss[391];

#define Ai_ss_rows 4590
#define Ai_ss_cols 1
#define Ai_ss_len 4590
extern int Ai_ss[4590];

#define Ax_ss_rows 4590
#define Ax_ss_cols 1
#define Ax_ss_len 4590
extern real Ax_ss[4590];

#define D_ss_rows 390
#define D_ss_cols 1
#define D_ss_len 390
extern real D_ss[390];

#define Lp_ss_rows 391
#define Lp_ss_cols 1
#define Lp_ss_len 391
extern int Lp_ss[391];

#define d_ss_rows 1
#define d_ss_cols 1
#define d_ss_len 1
extern int d_ss[1];

#define L_p_ss_rows 231
#define L_p_ss_cols 1
#define L_p_ss_len 231
extern int L_p_ss[231];

#define L_i_ss_rows 140
#define L_i_ss_cols 1
#define L_i_ss_len 140
extern int L_i_ss[140];

#define L_x_ss_rows 140
#define L_x_ss_cols 1
#define L_x_ss_len 140
extern real L_x_ss[140];

#define n_L_ss_rows 1
#define n_L_ss_cols 1
#define n_L_ss_len 1
extern int n_L_ss[1];
#ifdef lapack_linsolve 
extern __CLPK_integer ipiv[nn_lp];
#endif 
real *Lx_ss;
int *Li_ss;


// Functions
void custom_compute_parametric(REAL l[140], REAL f[230], REAL b[160], REAL par[20]);
void compute_parametric_pB(REAL y[160], REAL x[20]);
void custom_mult_Ltrans(REAL y[230], REAL x[140]);
/*
ldl_ss
*/
void custom_solve_kkt(REAL y[390], REAL x[390]);
void custom_compute_prefactor();
void custom_mult_L(REAL workDual[140], REAL x[230]);
void custom_prox(real y[nDual], real x[nDual]);


#endif
