/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#ifndef __user_probData_h__
#define __user_probData_h__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include "foo_data.h"
#include "user_matrix_ops.h"
#define real data_t_primal_out
#define REAL data_t_primal_out
#define nParam 8
#define nPrimal 78
#define nDual 28
#define nEqCon 64
#define rho_init 0.050000
#define rho_inv_init 20.000000
#define prox_var_init 0.000000
extern real rho;

extern real rhoinv; 

extern real prox_var; 

#define nn_lp 142
#define LNZ_ss 302
#define ANZ_ss 380
#define N_ss 142
#include "user_mv_mult.h" 


#define par_ex_rows 8
#define par_ex_cols 1
#define par_ex_len 8
extern real par_ex[8];

#define sol_x_rows 78
#define sol_x_cols 1
#define sol_x_len 78
extern real sol_x[78];

#define sol_lam_rows 28
#define sol_lam_cols 1
#define sol_lam_len 28
extern real sol_lam[28];

#define sol_y_rows 28
#define sol_y_cols 1
#define sol_y_len 28
extern real sol_y[28];

#define l_rows 28
#define l_cols 1
#define l_len 28
extern real l[28];

#define f_rows 78
#define f_cols 1
#define f_len 78
extern real f[78];

#define b_rows 64
#define b_cols 1
#define b_len 64
extern real b[64];

#define _var_1__b_rows 64
#define _var_1__b_cols 1
#define _var_1__b_len 64
extern real _var_1__b[64];

#define Ltrans_rind_rows 28
#define Ltrans_rind_cols 1
#define Ltrans_rind_len 28
extern int Ltrans_rind[28];

#define Ltrans_cind_rows 28
#define Ltrans_cind_cols 1
#define Ltrans_cind_len 28
extern int Ltrans_cind[28];

#define Ltrans_val_rows 28
#define Ltrans_val_cols 1
#define Ltrans_val_len 28
extern real Ltrans_val[28];

#define L_rind_rows 28
#define L_rind_cols 1
#define L_rind_len 28
extern int L_rind[28];

#define L_cind_rows 28
#define L_cind_cols 1
#define L_cind_len 28
extern int L_cind[28];

#define L_val_rows 28
#define L_val_cols 1
#define L_val_len 28
extern real L_val[28];
#ifdef lapack_linsolve 
extern __CLPK_integer ipiv[nn_lp];
#endif 
extern double *Lx_ss;
extern int *Li_ss;


// Functions
void custom_compute_parametric(REAL l[28], REAL f[78], REAL b[64], REAL par[8]);
void compute_parametric_pB(REAL y[64], REAL x[8]);
void custom_mult_Ltrans(REAL y[78], REAL x[28]);
/*
invert_FPGA_MAC
*/
void custom_solve_kkt(REAL y[142], REAL x[142]);
void custom_mult_L(REAL workDual[28], REAL x[78]);
void custom_prox(real y[nDual], real x[nDual]);


#endif
