/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#ifndef __try1_h__
#define __try1_h__

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <Accelerate/Accelerate.h>
#include "matrix_ops.h"
#include "splitLoad.h"

typedef double REAL;
#define printVec printDoubleVec


// Functions
void loadData();


#endif
