/***********************************************
 * Header file automatically generated by SPLIT
 *
 * More information : la.epfl.ch
 ***********************************************/
#include "try1.h"



void loadData() {
Data *dat = splitLoad("try1.dat");
freeData(dat);
}

